apiVersion: v1
kind: Service
metadata:
  name: "javalibertyapp-service"
spec:
  selector:
    app: "javalibertyapp-selector"
  type: NodePort
  ports:
  - name: http
    port: 9080
  - name: https
    port: 9443
